/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as RoomPreviewRouteImport } from './routes/room-preview'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as DreamRoomRouteImport } from './routes/dream-room'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BundleModernTealRouteImport } from './routes/bundle.modern-teal'
import { Route as BundleMidCenturyWarmRouteImport } from './routes/bundle.mid-century-warm'
import { Route as BundleJapandiMinimalRouteImport } from './routes/bundle.japandi-minimal'

const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomPreviewRoute = RoomPreviewRouteImport.update({
  id: '/room-preview',
  path: '/room-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamRoomRoute = DreamRoomRouteImport.update({
  id: '/dream-room',
  path: '/dream-room',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleModernTealRoute = BundleModernTealRouteImport.update({
  id: '/bundle/modern-teal',
  path: '/bundle/modern-teal',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleMidCenturyWarmRoute = BundleMidCenturyWarmRouteImport.update({
  id: '/bundle/mid-century-warm',
  path: '/bundle/mid-century-warm',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleJapandiMinimalRoute = BundleJapandiMinimalRouteImport.update({
  id: '/bundle/japandi-minimal',
  path: '/bundle/japandi-minimal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dream-room': typeof DreamRoomRoute
  '/lookbook': typeof LookbookRoute
  '/quiz': typeof QuizRoute
  '/room-preview': typeof RoomPreviewRoute
  '/shopping': typeof ShoppingRoute
  '/bundle/japandi-minimal': typeof BundleJapandiMinimalRoute
  '/bundle/mid-century-warm': typeof BundleMidCenturyWarmRoute
  '/bundle/modern-teal': typeof BundleModernTealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dream-room': typeof DreamRoomRoute
  '/lookbook': typeof LookbookRoute
  '/quiz': typeof QuizRoute
  '/room-preview': typeof RoomPreviewRoute
  '/shopping': typeof ShoppingRoute
  '/bundle/japandi-minimal': typeof BundleJapandiMinimalRoute
  '/bundle/mid-century-warm': typeof BundleMidCenturyWarmRoute
  '/bundle/modern-teal': typeof BundleModernTealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dream-room': typeof DreamRoomRoute
  '/lookbook': typeof LookbookRoute
  '/quiz': typeof QuizRoute
  '/room-preview': typeof RoomPreviewRoute
  '/shopping': typeof ShoppingRoute
  '/bundle/japandi-minimal': typeof BundleJapandiMinimalRoute
  '/bundle/mid-century-warm': typeof BundleMidCenturyWarmRoute
  '/bundle/modern-teal': typeof BundleModernTealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dream-room'
    | '/lookbook'
    | '/quiz'
    | '/room-preview'
    | '/shopping'
    | '/bundle/japandi-minimal'
    | '/bundle/mid-century-warm'
    | '/bundle/modern-teal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dream-room'
    | '/lookbook'
    | '/quiz'
    | '/room-preview'
    | '/shopping'
    | '/bundle/japandi-minimal'
    | '/bundle/mid-century-warm'
    | '/bundle/modern-teal'
  id:
    | '__root__'
    | '/'
    | '/dream-room'
    | '/lookbook'
    | '/quiz'
    | '/room-preview'
    | '/shopping'
    | '/bundle/japandi-minimal'
    | '/bundle/mid-century-warm'
    | '/bundle/modern-teal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DreamRoomRoute: typeof DreamRoomRoute
  LookbookRoute: typeof LookbookRoute
  QuizRoute: typeof QuizRoute
  RoomPreviewRoute: typeof RoomPreviewRoute
  ShoppingRoute: typeof ShoppingRoute
  BundleJapandiMinimalRoute: typeof BundleJapandiMinimalRoute
  BundleMidCenturyWarmRoute: typeof BundleMidCenturyWarmRoute
  BundleModernTealRoute: typeof BundleModernTealRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-preview': {
      id: '/room-preview'
      path: '/room-preview'
      fullPath: '/room-preview'
      preLoaderRoute: typeof RoomPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dream-room': {
      id: '/dream-room'
      path: '/dream-room'
      fullPath: '/dream-room'
      preLoaderRoute: typeof DreamRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle/modern-teal': {
      id: '/bundle/modern-teal'
      path: '/bundle/modern-teal'
      fullPath: '/bundle/modern-teal'
      preLoaderRoute: typeof BundleModernTealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle/mid-century-warm': {
      id: '/bundle/mid-century-warm'
      path: '/bundle/mid-century-warm'
      fullPath: '/bundle/mid-century-warm'
      preLoaderRoute: typeof BundleMidCenturyWarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle/japandi-minimal': {
      id: '/bundle/japandi-minimal'
      path: '/bundle/japandi-minimal'
      fullPath: '/bundle/japandi-minimal'
      preLoaderRoute: typeof BundleJapandiMinimalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DreamRoomRoute: DreamRoomRoute,
  LookbookRoute: LookbookRoute,
  QuizRoute: QuizRoute,
  RoomPreviewRoute: RoomPreviewRoute,
  ShoppingRoute: ShoppingRoute,
  BundleJapandiMinimalRoute: BundleJapandiMinimalRoute,
  BundleMidCenturyWarmRoute: BundleMidCenturyWarmRoute,
  BundleModernTealRoute: BundleModernTealRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
